services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis

  task-manager-app:
    container_name: task-manager-app
    build:
      context: ./
    env_file:
      - .env
    ports:
      - ${TASK_MANAGER_APP_PORT}:${TASK_MANAGER_APP_PORT}

volumes:
  pg-data: